/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 */

#ifndef _RTGALAXY_IO_H_
#define _RTGALAXY_IO_H_

#include <asm/addrspace.h>

/*
 * Internal registers are accessed through KSEG1
 */
#define RTGALAXY_REGS_VA(x)		((void __iomem *)(KSEG1ADDR(x)))

#define rtgalaxy_readb(a)		(*(volatile unsigned char  *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_readw(a)		(*(volatile unsigned short *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_readl(a)		(*(volatile unsigned int   *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_writeb(v, a)		(*(volatile unsigned char  *) RTGALAXY_REGS_VA((a)) = (v))
#define rtgalaxy_writew(v, a)		(*(volatile unsigned short *) RTGALAXY_REGS_VA((a)) = (v))
#define rtgalaxy_writel(v, a)		(*(volatile unsigned int   *) RTGALAXY_REGS_VA((a)) = (v))

#define RTGALAXY_SOC_BASE		0x18000000
#define RTGALAXY_REG_BASE		0x18010000

#define rtgalaxy_soc_readb(a)		rtgalaxy_readb(RTGALAXY_SOC_BASE+a)
#define rtgalaxy_soc_readw(a)		rtgalaxy_readw(RTGALAXY_SOC_BASE+a)
#define rtgalaxy_soc_readl(a)		rtgalaxy_readl(RTGALAXY_SOC_BASE+a)
#define rtgalaxy_soc_writeb(v, a)	rtgalaxy_writeb(v, RTGALAXY_SOC_BASE+a)
#define rtgalaxy_soc_writew(v, a)	rtgalaxy_writew(v, RTGALAXY_SOC_BASE+a)
#define rtgalaxy_soc_writel(v, a)	rtgalaxy_writel(v, RTGALAXY_SOC_BASE+a)

#define rtgalaxy_reg_readb(a)		rtgalaxy_readb(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_readw(a)		rtgalaxy_readw(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_readl(a)		rtgalaxy_readl(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writeb(v, a)	rtgalaxy_writeb(v, RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writew(v, a)	rtgalaxy_writew(v, RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writel(v, a)	rtgalaxy_writel(v, RTGALAXY_REG_BASE+a)

/*
 * SoC Clock Register
 */

#define RTGALAXY_SOC_CLOCK_BASE_OFFSET		0x0000

#define RTGALAXY_SOC_CLOCK_ENABLE_OFFSET	0x0c

#define RTGALAXY_SOC_CLOCK_BASE			(RTGALAXY_SOC_CLOCK_BASE_OFFSET)
#define RTGALAXY_SOC_CLOCK_ENABLE		(RTGALAXY_SOC_CLOCK_BASE+RTGALAXY_SOC_CLOCK_ENABLE_OFFSET)

#define RTGALAXY_SOC_CLOCK_ENABLE_ETH		(1 << 9)

/*
 * rt-galaxy registers
 */

#define RTGALAXY_SYS_BASE_OFFSET		0x0000
#define RTGALAXY_EHCI_BASE_OFFSET		0x3000
#define RTGALAXY_OHCI_BASE_OFFSET		0x3400
#define RTGALAXY_USBH_BASE_OFFSET		0x3800
#define RTGALAXY_MCP_BASE_OFFSET		0x5100
#define RTGALAXY_ETH_BASE_OFFSET		0x6000
#define RTGALAXY_TVE_BASE_OFFSET		0x8000
#define RTGALAXY_TVD_BASE_OFFSET		0x9000
#define RTGALAXY_SB2_BASE_OFFSET		0xa000
#define RTGALAXY_MISC_BASE_OFFSET		0xb000
#define RTGALAXY_GPIO_BASE_OFFSET		0xb100
#define RTGALAXY_UART_BASE_OFFSET		0xb200
#define RTGALAXY_I2C0_BASE_OFFSET		0xb300
#define RTGALAXY_IRDA_BASE_OFFSET		0xb400
#define RTGALAXY_TIMR_BASE_OFFSET		0xb500
#define RTGALAXY_RTC_BASE_OFFSET		0xb600
#define RTGALAXY_VFDC_BASE_OFFSET		0xb700
#define RTGALAXY_PCMCIA_BASE_OFFSET		0xb800
#define RTGALAXY_CEC_BASE_OFFSET		0xb900
#define RTGALAXY_SC0_BASE_OFFSET		0xba00
#define RTGALAXY_I2C1_BASE_OFFSET		0xbb00
#define RTGALAXY_SC1_BASE_OFFSET		0xbc00

/*
 * Misc (PLL, IRQ ??)
 */

#define RTGALAXY_MISC_PSELH_OFFSET		0x000
#define RTGALAXY_MISC_PSELL_OFFSET		0x004
#define RTGALAXY_MISC_UMSK_ISR_OFFSET		0x008
#define RTGALAXY_MISC_ISR_OFFSET		0x00c
#define RTGALAXY_MISC_UMSK_ISR_GP0A_OFFSET	0x010
#define RTGALAXY_MISC_UMSK_ISR_GP0DA_OFFSET	0x014
#define RTGALAXY_MISC_UMSK_ISR_KPADAH_OFFSET	0x018
#define RTGALAXY_MISC_UMSK_ISR_KPADAL_OFFSET	0x01c
#define RTGALAXY_MISC_UMSK_ISR_KPADDAH_OFFSET	0x020
#define RTGALAXY_MISC_UMSK_ISR_KPADDAL_OFFSET	0x024
#define RTGALAXY_MISC_UMSK_ISR_SW_OFFSET	0x028
#define RTGALAXY_MISC_DBG_OFFSET		0x02c
#define RTGALAXY_MISC_DUMMY_OFFSET		0x030
#define RTGALAXY_MISC_PSEL2_OFFSET		0x034
#define RTGALAXY_MISC_UMSK_ISR_GP1A_OFFSET	0x038
#define RTGALAXY_MISC_UMSK_ISR_GP1DA_OFFSET	0x03c

#define RTGALAXY_MISC_BASE			(RTGALAXY_MISC_BASE_OFFSET)
#define RTGALAXY_MISC_PSELH			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSELH_OFFSET)
#define RTGALAXY_MISC_PSELL			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSELL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_OFFSET)
#define RTGALAXY_MISC_ISR			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_ISR_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP0A		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP0A_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP0DA		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP0DA_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADAH		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADAH_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADAL		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADAL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADDAH		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADDAH_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADDAL		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADDAL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_SW		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_SW_OFFSET)
#define RTGALAXY_MISC_DBG			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_DBG_OFFSET)
#define RTGALAXY_MISC_DUMMY			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_DUMMY_OFFSET)
#define RTGALAXY_MISC_PSEL2			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSEL2_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP1A		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP1A_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP1DA		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP1DA_OFFSET)

/*
 * UART0/UART1 (8250 compatible)
 */

#define RTGALAXY_UART_U0RBR_THR_DLL_OFFSET	0x000
#define RTGALAXY_UART_U0IER_DLH_OFFSET		0x004
#define RTGALAXY_UART_U0IIR_FCR_OFFSET		0x008
#define RTGALAXY_UART_U0LCR_OFFSET		0x00c
#define RTGALAXY_UART_U0MCR_OFFSET		0x010
#define RTGALAXY_UART_U0LSR_OFFSET		0x014
#define RTGALAXY_UART_U0MSR_OFFSET		0x018
#define RTGALAXY_UART_U0SCR_OFFSET		0x01c
#define RTGALAXY_UART_U1RBR_THR_DLL_OFFSET	0x020
#define RTGALAXY_UART_U1IER_DLH_OFFSET		0x024
#define RTGALAXY_UART_U1IIR_FCR_OFFSET		0x028
#define RTGALAXY_UART_U1LCR_OFFSET		0x02c
#define RTGALAXY_UART_U1MCR_OFFSET		0x030
#define RTGALAXY_UART_U1LSR_OFFSET		0x034
#define RTGALAXY_UART_U1MSR_OFFSET		0x038
#define RTGALAXY_UART_U1SCR_OFFSET		0x03c

#define RTGALAXY_UART_BASE			(RTGALAXY_UART_BASE_OFFSET)
#define RTGALAXY_UART_U0RBR_THR_DLL		(RTGALAXY_UART_BASE+RTGALAXY_UART_U0RBR_THR_DLL_OFFSET)
#define RTGALAXY_UART_U0IER_DLH			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0IER_DLH_OFFSET)
#define RTGALAXY_UART_U0IIR_FCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0IIR_FCR_OFFSET)
#define RTGALAXY_UART_U0LCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0LCR_OFFSET)
#define RTGALAXY_UART_U0MCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0MCR_OFFSET)
#define RTGALAXY_UART_U0LSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0LSR_OFFSET)
#define RTGALAXY_UART_U0MSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0MSR_OFFSET)
#define RTGALAXY_UART_U0SCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0SCR_OFFSET)
#define RTGALAXY_UART_U1RBR_THR_DLL		(RTGALAXY_UART_BASE+RTGALAXY_UART_U1RBR_THR_DLL_OFFSET)
#define RTGALAXY_UART_U1IER_DLH			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1IER_DLH_OFFSET)
#define RTGALAXY_UART_U1IIR_FCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1IIR_FCR_OFFSET)
#define RTGALAXY_UART_U1LCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1LCR_OFFSET)
#define RTGALAXY_UART_U1MCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1MCR_OFFSET)
#define RTGALAXY_UART_U1LSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1LSR_OFFSET)
#define RTGALAXY_UART_U1MSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1MSR_OFFSET)
#define RTGALAXY_UART_U1SCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1SCR_OFFSET)

#define RTGALAXY_UART0_BASE			RTGALAXY_UART_U0RBR_THR_DLL
#define RTGALAXY_UART1_BASE			RTGALAXY_UART_U1RBR_THR_DLL

/*
 * Timer
 */

#define RTGALAXY_TIMR_TC0TVR_OFFSET		0x000
#define RTGALAXY_TIMR_TC1TVR_OFFSET		0x004
#define RTGALAXY_TIMR_TC2TVR_OFFSET		0x008
#define RTGALAXY_TIMR_TC0CVR_OFFSET		0x00c
#define RTGALAXY_TIMR_TC1CVR_OFFSET		0x010
#define RTGALAXY_TIMR_TC2CVR_OFFSET		0x014
#define RTGALAXY_TIMR_TC0CR_OFFSET		0x018
#define RTGALAXY_TIMR_TC1CR_OFFSET		0x01c
#define RTGALAXY_TIMR_TC2CR_OFFSET		0x020
#define RTGALAXY_TIMR_TC0ICR_OFFSET		0x024
#define RTGALAXY_TIMR_TC1ICR_OFFSET		0x028
#define RTGALAXY_TIMR_TC2ICR_OFFSET		0x02c
#define RTGALAXY_TIMR_TCWCR_OFFSET		0x030
#define RTGALAXY_TIMR_TCWTR_OFFSET		0x034
#define RTGALAXY_TIMR_CLK27M_CLK90K_CNT_OFFSET	0x038
#define RTGALAXY_TIMR_CLK90K_TM_LO_OFFSET	0x03c
#define RTGALAXY_TIMR_CLK90K_TM_HI_OFFSET	0x040

#define RTGALAXY_TIMR_BASE			(RTGALAXY_TIMR_BASE_OFFSET)
#define RTGALAXY_TIMR_TC0TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0TVR_OFFSET)
#define RTGALAXY_TIMR_TC1TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1TVR_OFFSET)
#define RTGALAXY_TIMR_TC2TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2TVR_OFFSET)
#define RTGALAXY_TIMR_TC0CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0CVR_OFFSET)
#define RTGALAXY_TIMR_TC1CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1CVR_OFFSET)
#define RTGALAXY_TIMR_TC2CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2CVR_OFFSET)
#define RTGALAXY_TIMR_TC0CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0CR_OFFSET)
#define RTGALAXY_TIMR_TC1CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1CR_OFFSET)
#define RTGALAXY_TIMR_TC2CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2CR_OFFSET)
#define RTGALAXY_TIMR_TC0ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0ICR_OFFSET)
#define RTGALAXY_TIMR_TC1ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1ICR_OFFSET)
#define RTGALAXY_TIMR_TC2ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2ICR_OFFSET)
#define RTGALAXY_TIMR_TCWCR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TCWCR_OFFSET)
#define RTGALAXY_TIMR_TCWTR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TCWTR_OFFSET)
#define RTGALAXY_TIMR_CLK27M_CLK90K_CNT		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK27M_CLK90K_CNT_OFFSET)
#define RTGALAXY_TIMR_CLK90K_TM_LO		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK90K_TM_LO_OFFSET)
#define RTGALAXY_TIMR_CLK90K_TM_HI		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK90K_TM_HI_OFFSET)

/*
 * RTC
 */

#define RTGALAXY_RTC_SEC_OFFSET			0x000
#define RTGALAXY_RTC_MIN_OFFSET			0x004
#define RTGALAXY_RTC_HR_OFFSET			0x008
#define RTGALAXY_RTC_DATE1_OFFSET		0x00c
#define RTGALAXY_RTC_DATE2_OFFSET		0x010
#define RTGALAXY_RTC_ALMMIN_OFFSET		0x014
#define RTGALAXY_RTC_ALMHR_OFFSET		0x018
#define RTGALAXY_RTC_ALMDATE1_OFFSET		0x01c
#define RTGALAXY_RTC_ALMDATE2_OFFSET		0x020
#define RTGALAXY_RTC_STOP_OFFSET		0x024
#define RTGALAXY_RTC_ACR_OFFSET			0x028
#define RTGALAXY_RTC_EN_OFFSET			0x02c
#define RTGALAXY_RTC_CR_OFFSET			0x030

#define RTGALAXY_RTC_BASE			(RTGALAXY_RTC_BASE_OFFSET)
#define RTGALAXY_RTC_SEC			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_SEC_OFFSET)
#define RTGALAXY_RTC_MIN			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_MIN_OFFSET)
#define RTGALAXY_RTC_HR				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_HR_OFFSET)
#define RTGALAXY_RTC_DATE1			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_DATE1_OFFSET)
#define RTGALAXY_RTC_DATE2			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_DATE2_OFFSET)
#define RTGALAXY_RTC_ALMMIN			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMMIN_OFFSET)
#define RTGALAXY_RTC_ALMHR			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMHR_OFFSET)
#define RTGALAXY_RTC_ALMDATE1			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMDATE1_OFFSET)
#define RTGALAXY_RTC_ALMDATE2			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMDATE2_OFFSET)
#define RTGALAXY_RTC_STOP			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_STOP_OFFSET)
#define RTGALAXY_RTC_ACR			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ACR_OFFSET)
#define RTGALAXY_RTC_EN				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_EN_OFFSET)
#define RTGALAXY_RTC_CR				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_CR_OFFSET)

/*
 * USB EHCI
 */

#define RTGALAXY_USB_EHCI_INSNREG05_VBUSY(v)    ((v & 0x1) << 17)
#define RTGALAXY_USB_EHCI_INSNREG05_VPORT(v)    ((v & 0xf) << 13)
#define RTGALAXY_USB_EHCI_INSNREG05_VLOADM(v)   ((v & 0x1) << 12)
#define RTGALAXY_USB_EHCI_INSNREG05_VCTRL(v)    ((v & 0xf) <<  8)

#define RTGALAXY_USB_EHCI_INSNREG05_VBUSY_MASK  RTGALAXY_USB_EHCI_INSNREG05_VBUSY(0x1)
#define RTGALAXY_USB_EHCI_INSNREG05_VPORT_MASK  RTGALAXY_USB_EHCI_INSNREG05_VPORT(0xf)
#define RTGALAXY_USB_EHCI_INSNREG05_VLOADM_MASK RTGALAXY_USB_EHCI_INSNREG05_VLOADM(0x1)
#define RTGALAXY_USB_EHCI_INSNREG05_VCTRL_MASK  RTGALAXY_USB_EHCI_INSNREG05_VCTRL(0xf)

#define RTGALAXY_USB_EHCI_HCCAPBASE_OFFSET        0x0000
#define RTGALAXY_USB_EHCI_HCSPARAMS_OFFSET        0x0004
#define RTGALAXY_USB_EHCI_HCCPARAMS_OFFSET        0x0008
#define RTGALAXY_USB_EHCI_USBCMD_OFFSET           0x0010
#define RTGALAXY_USB_EHCI_USBSTS_OFFSET           0x0014
#define RTGALAXY_USB_EHCI_USBINTR_OFFSET          0x0018
#define RTGALAXY_USB_EHCI_FRINDEX_OFFSET          0x001c
#define RTGALAXY_USB_EHCI_CTRLDSSEGMENT_OFFSET    0x0020
#define RTGALAXY_USB_EHCI_PERIODICLISTBASE_OFFSET 0x0024
#define RTGALAXY_USB_EHCI_ASYNCLISTADDR_OFFSET    0x0028
#define RTGALAXY_USB_EHCI_CONFIGFLAG_OFFSET       0x0050
#define RTGALAXY_USB_EHCI_PORTSC_0_OFFSET         0x0054
#define RTGALAXY_USB_EHCI_INSNREG00_OFFSET        0x0090
#define RTGALAXY_USB_EHCI_INSNREG01_OFFSET        0x0094
#define RTGALAXY_USB_EHCI_INSNREG02_OFFSET        0x0098
#define RTGALAXY_USB_EHCI_INSNREG03_OFFSET        0x009c
#define RTGALAXY_USB_EHCI_INSNREG04_OFFSET        0x00a0
#define RTGALAXY_USB_EHCI_INSNREG05_OFFSET        0x00a4

#define RTGALAXY_USB_EHCI_BASE             (RTGALAXY_EHCI_BASE_OFFSET)
#define RTGALAXY_USB_EHCI_HCCAPBASE        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_HCCAPBASE_OFFSET)
#define RTGALAXY_USB_EHCI_HCSPARAMS        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_HCSPARAMS_OFFSET)
#define RTGALAXY_USB_EHCI_HCCPARAMS        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_HCCPARAMS_OFFSET)
#define RTGALAXY_USB_EHCI_USBCMD           (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_USBCMD_OFFSET)
#define RTGALAXY_USB_EHCI_USBSTS           (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_USBSTS_OFFSET)
#define RTGALAXY_USB_EHCI_USBINTR          (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_USBINTR_OFFSET)
#define RTGALAXY_USB_EHCI_FRINDEX          (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_FRINDEX_OFFSET)
#define RTGALAXY_USB_EHCI_CTRLDSSEGMENT    (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_CTRLDSSEGMENT_OFFSET)
#define RTGALAXY_USB_EHCI_PERIODICLISTBASE (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_PERIODICLISTBASE_OFFSET)
#define RTGALAXY_USB_EHCI_ASYNCLISTADDR    (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_ASYNCLISTADDR_OFFSET)
#define RTGALAXY_USB_EHCI_CONFIGFLAG       (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_CONFIGFLAG_OFFSET)
#define RTGALAXY_USB_EHCI_PORTSC_0         (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_PORTSC_0_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG00        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG00_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG01        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG01_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG02        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG02_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG03        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG03_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG04        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG04_OFFSET)
#define RTGALAXY_USB_EHCI_INSNREG05        (RTGALAXY_USB_EHCI_BASE+RTGALAXY_USB_EHCI_INSNREG05_OFFSET)

/*
 * USB OHCI
 */

#define RTGALAXY_USB_OHCI_REVISION_OFFSET           0x0000
#define RTGALAXY_USB_OHCI_CONTROL_OFFSET            0x0004
#define RTGALAXY_USB_OHCI_CMDSTATUS_OFFSET          0x0008
#define RTGALAXY_USB_OHCI_INTSTATUS_OFFSET          0x000c
#define RTGALAXY_USB_OHCI_INTENABLE_OFFSET          0x0010
#define RTGALAXY_USB_OHCI_INTDISABLE_OFFSET         0x0014
#define RTGALAXY_USB_OHCI_HCCA_OFFSET               0x0018
#define RTGALAXY_USB_OHCI_PERIOD_CURRENTED_OFFSET   0x001c
#define RTGALAXY_USB_OHCI_CONTROL_HEADED_OFFSET     0x0020
#define RTGALAXY_USB_OHCI_CONTROL_CURRENTED_OFFSET  0x0024
#define RTGALAXY_USB_OHCI_BULK_HEADED_OFFSET        0x0028
#define RTGALAXY_USB_OHCI_BULK_CURRENTED_OFFSET     0x002c
#define RTGALAXY_USB_OHCI_DONE_HEAD_OFFSET          0x0030
#define RTGALAXY_USB_OHCI_FM_INTERVAL_OFFSET        0x0034
#define RTGALAXY_USB_OHCI_FM_REMAINING_OFFSET       0x0038
#define RTGALAXY_USB_OHCI_FM_NUMBER_OFFSET          0x003c
#define RTGALAXY_USB_OHCI_PERIODIC_START_OFFSET     0x0040
#define RTGALAXY_USB_OHCI_LS_THRESHOLD_OFFSET       0x0044
#define RTGALAXY_USB_OHCI_RH_DESC_A_OFFSET          0x0048
#define RTGALAXY_USB_OHCI_RH_DESC_B_OFFSET          0x004c
#define RTGALAXY_USB_OHCI_RH_STATUS_OFFSET          0x0050
#define RTGALAXY_USB_OHCI_PORT_STATUS_1_OFFSET      0x0054

#define RTGALAXY_USB_OHCI_BASE              (RTGALAXY_OHCI_BASE_OFFSET)
#define RTGALAXY_USB_OHCI_REVISION          (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_REVISION_OFFSET)
#define RTGALAXY_USB_OHCI_CONTROL           (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_CONTROL_OFFSET)
#define RTGALAXY_USB_OHCI_CMDSTATUS         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_CMDSTATUS_OFFSET)
#define RTGALAXY_USB_OHCI_INTSTATUS         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_INTSTATUS_OFFSET)
#define RTGALAXY_USB_OHCI_INTENABLE         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_INTENABLE_OFFSET)
#define RTGALAXY_USB_OHCI_INTDISABLE        (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_INTDISABLE_OFFSET)
#define RTGALAXY_USB_OHCI_HCCA              (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_HCCA_OFFSET)
#define RTGALAXY_USB_OHCI_PERIOD_CURRENTED  (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_PERIOD_CURRENTED_OFFSET)
#define RTGALAXY_USB_OHCI_CONTROL_HEADED    (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_CONTROL_HEADED_OFFSET)
#define RTGALAXY_USB_OHCI_CONTROL_CURRENTED (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_CONTROL_CURRENTED_OFFSET)
#define RTGALAXY_USB_OHCI_BULK_HEADED       (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_BULK_HEADED_OFFSET)
#define RTGALAXY_USB_OHCI_BULK_CURRENTED    (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_BULK_CURRENTED_OFFSET)
#define RTGALAXY_USB_OHCI_DONE_HEAD         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_DONE_HEAD_OFFSET)
#define RTGALAXY_USB_OHCI_FM_INTERVAL       (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_FM_INTERVAL_OFFSET)
#define RTGALAXY_USB_OHCI_FM_REMAINING      (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_FM_REMAINING_OFFSET)
#define RTGALAXY_USB_OHCI_FM_NUMBER         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_FM_NUMBER_OFFSET)
#define RTGALAXY_USB_OHCI_PERIODIC_START    (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_PERIODIC_START_OFFSET)
#define RTGALAXY_USB_OHCI_LS_THRESHOLD      (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_LS_THRESHOLD_OFFSET)
#define RTGALAXY_USB_OHCI_RH_DESC_A         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_RH_DESC_A_OFFSET)
#define RTGALAXY_USB_OHCI_RH_DESC_B         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_RH_DESC_B_OFFSET)
#define RTGALAXY_USB_OHCI_RH_STATUS         (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_RH_STATUS_OFFSET)
#define RTGALAXY_USB_OHCI_PORT_STATUS_1     (RTGALAXY_USB_OHCI_BASE+RTGALAXY_USB_OHCI_PORT_STATUS_1_OFFSET)

/*
 * USB HOST
 */

#define RTGALAXY_USB_HOST_VERSION_NO_USE_DONE       (1 << 1)

#define RTGALAXY_USB_HOST1_WRAPPER_OFFSET           0x0000
#define RTGALAXY_USB_HOST2_WRAPPER_OFFSET           0x0020

#define RTGALAXY_USB_HOST_VSTATUS_OFFSET            0x0004
#define RTGALAXY_USB_HOST_USBIP_INPUT_OFFSET        0x0008
#define RTGALAXY_USB_HOST_RESET_UTMI_OFFSET         0x000c
#define RTGALAXY_USB_HOST_SELF_LOOPBACK_OFFSET      0x0010

#define RTGALAXY_USB_HOST_VERSION_OFFSET            0x0014
#define RTGALAXY_USB_HOST_USBIP_NEWINPUT_OFFSET     0x0034
#define RTGALAXY_USB_HOST_USBPHY_SLB0_OFFSET        0x0038
#define RTGALAXY_USB_HOST_USBPHY_SLB1_OFFSET        0x003c
#define RTGALAXY_USB_HOST_OTG_OFFSET                0x0040
#define RTGALAXY_USB_HOST_OTGMUX_OFFSET             0x0044

#define RTGALAXY_USB_HOST_BASE            (RTGALAXY_USBH_BASE_OFFSET)
#define RTGALAXY_USB_HOST1_WRAPPER        (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST1_WRAPPER_OFFSET)
#define RTGALAXY_USB_HOST2_WRAPPER        (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST2_WRAPPER_OFFSET)
#define RTGALAXY_USB_HOST1_VSTATUS        (RTGALAXY_USB_HOST1_WRAPPER+RTGALAXY_USB_HOST_VSTATUS_OFFSET)
#define RTGALAXY_USB_HOST1_USBIP_INPUT    (RTGALAXY_USB_HOST1_WRAPPER+RTGALAXY_USB_HOST_USBIP_INPUT_OFFSET)
#define RTGALAXY_USB_HOST1_RESET_UTMI     (RTGALAXY_USB_HOST1_WRAPPER+RTGALAXY_USB_HOST_RESET_UTMI_OFFSET)
#define RTGALAXY_USB_HOST1_SELF_LOOPBACK  (RTGALAXY_USB_HOST1_WRAPPER+RTGALAXY_USB_HOST_SELF_LOOPBACK_OFFSET)
#define RTGALAXY_USB_HOST2_VSTATUS        (RTGALAXY_USB_HOST2_WRAPPER+RTGALAXY_USB_HOST_VSTATUS_OFFSET)
#define RTGALAXY_USB_HOST2_USBIP_INPUT    (RTGALAXY_USB_HOST2_WRAPPER+RTGALAXY_USB_HOST_USBIP_INPUT_OFFSET)
#define RTGALAXY_USB_HOST2_RESET_UTMI     (RTGALAXY_USB_HOST2_WRAPPER+RTGALAXY_USB_HOST_RESET_UTMI_OFFSET)
#define RTGALAXY_USB_HOST2_SELF_LOOPBACK  (RTGALAXY_USB_HOST2_WRAPPER+RTGALAXY_USB_HOST_SELF_LOOPBACK_OFFSET)

#define RTGALAXY_USB_HOST_VERSION         (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_VERSION_OFFSET)
#define RTGALAXY_USB_HOST_USBIP_NEWINPUT  (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_USBIP_NEWINPUT_OFFSET)
#define RTGALAXY_USB_HOST_USBPHY_SLB0     (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_USBPHY_SLB0_OFFSET)
#define RTGALAXY_USB_HOST_USBPHY_SLB1     (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_USBPHY_SLB1_OFFSET)
#define RTGALAXY_USB_HOST_OTG             (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_OTG_OFFSET)
#define RTGALAXY_USB_HOST_OTGMUX          (RTGALAXY_USB_HOST_BASE+RTGALAXY_USB_HOST_OTGMUX_OFFSET)

/*
 * SB2
 */

#define RTGALAXY_SB2_HD_SEM_OFFSET		0x000
#define RTGALAXY_SB2_INV_INTEN_OFFSET		0x004
#define RTGALAXY_SB2_INV_INTSTAT_OFFSET		0x008
#define RTGALAXY_SB2_INV_ADDR_OFFSET		0x00c

#define RTGALAXY_SB2_CHIP_ID_OFFSET		0x200
#define RTGALAXY_SB2_CHIP_INFO_OFFSET		0x204

#define RTGALAXY_SB2_DBG_START_REG0_OFFSET	0x458
#define RTGALAXY_SB2_DBG_START_REG1_OFFSET	0x45c
#define RTGALAXY_SB2_DBG_START_REG2_OFFSET	0x460
#define RTGALAXY_SB2_DBG_START_REG3_OFFSET	0x464
#define RTGALAXY_SB2_DBG_START_REG4_OFFSET	0x468
#define RTGALAXY_SB2_DBG_START_REG5_OFFSET	0x46c
#define RTGALAXY_SB2_DBG_START_REG6_OFFSET	0x470
#define RTGALAXY_SB2_DBG_START_REG7_OFFSET	0x474

#define RTGALAXY_SB2_DBG_END_REG0_OFFSET	0x478
#define RTGALAXY_SB2_DBG_END_REG1_OFFSET	0x47c
#define RTGALAXY_SB2_DBG_END_REG2_OFFSET	0x480
#define RTGALAXY_SB2_DBG_END_REG3_OFFSET	0x484
#define RTGALAXY_SB2_DBG_END_REG4_OFFSET	0x488
#define RTGALAXY_SB2_DBG_END_REG5_OFFSET	0x48c
#define RTGALAXY_SB2_DBG_END_REG6_OFFSET	0x490
#define RTGALAXY_SB2_DBG_END_REG7_OFFSET	0x494

#define RTGALAXY_SB2_DBG_CTRL_REG0_OFFSET	0x498
#define RTGALAXY_SB2_DBG_CTRL_REG1_OFFSET	0x49c
#define RTGALAXY_SB2_DBG_CTRL_REG2_OFFSET	0x4a0
#define RTGALAXY_SB2_DBG_CTRL_REG3_OFFSET	0x4a4
#define RTGALAXY_SB2_DBG_CTRL_REG4_OFFSET	0x4a8
#define RTGALAXY_SB2_DBG_CTRL_REG5_OFFSET	0x4ac
#define RTGALAXY_SB2_DBG_CTRL_REG6_OFFSET	0x4b0
#define RTGALAXY_SB2_DBG_CTRL_REG7_OFFSET	0x4b4

#define RTGALAXY_SB2_DBG_ADDR_AUDIO_OFFSET	0x4b8
#define RTGALAXY_SB2_DBG_ADDR_VIDEO_OFFSET	0x4bc
#define RTGALAXY_SB2_DBG_ADDR_SYSTEM_OFFSET	0x4c0

#define RTGALAXY_SB2_DBG_INT_OFFSET		0x4e0

#define RTGALAXY_SB2_BASE			(RTGALAXY_SB2_BASE_OFFSET)
#define RTGALAXY_SB2_HD_SEM			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_HD_SEM_OFFSET)
#define RTGALAXY_SB2_INV_INTEN			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_INTEN_OFFSET)
#define RTGALAXY_SB2_INV_INTSTAT		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_INTSTAT_OFFSET)
#define RTGALAXY_SB2_INV_ADDR			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_ADDR_OFFSET)

#define RTGALAXY_SB2_CHIP_ID			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_CHIP_ID_OFFSET)
#define RTGALAXY_SB2_CHIP_INFO			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_CHIP_INFO_OFFSET)

#define RTGALAXY_SB2_DBG_START_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_END_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_CTRL_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_ADDR_AUDIO		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_AUDIO_OFFSET)
#define RTGALAXY_SB2_DBG_ADDR_VIDEO		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_VIDEO_OFFSET)
#define RTGALAXY_SB2_DBG_ADDR_SYSTEM		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_SYSTEM_OFFSET)

#define RTGALAXY_SB2_DBG_INT			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_INT_OFFSET)

#endif
