/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 */

#ifndef _RTGALAXY_IRQ_H
#define _RTGALAXY_IRQ_H

#define MIPS_CPU_IRQ_BASE		0

#ifdef CONFIG_RTGALAXY_EXTERNAL_TIMER
#define MIPS_CPU_TIMER_IRQ		RTGALAXY_IRQ_EXT_TIMER
#else
#define MIPS_CPU_TIMER_IRQ		RTGALAXY_IRQ_TIMER
#endif

#define RTGALAXY_IRQ_BASE		2
#define RTGALAXY_INTERNAL_IRQ_BASE	8

#define RTGALAXY_MISC_IRQ_UART0		2
#define RTGALAXY_MISC_IRQ_UART1		3
#define RTGALAXY_MISC_IRQ_I2C0		4
#define RTGALAXY_MISC_IRQ_IRDA		5

#define RTGALAXY_MISC_IRQ_TIMER2	8

#define RTGALAXY_MISC_IRQ_RTC_HALF_HZ	9
#define RTGALAXY_MISC_IRQ_RTC1		10
#define RTGALAXY_MISC_IRQ_RTC2		11
#define RTGALAXY_MISC_IRQ_RTC3		12
#define RTGALAXY_MISC_IRQ_RTC4		13

#define RTGALAXY_MISC_IRQ_VFD_DONE	14
#define RTGALAXY_MISC_IRQ_KP_DOWN	15
#define RTGALAXY_MISC_IRQ_KP_UP		16
#define RTGALAXY_MISC_IRQ_SW_DOWN	17
#define RTGALAXY_MISC_IRQ_SW_UP		18

#define RTGALAXY_MISC_IRQ_GPIO		20
#define RTGALAXY_MISC_IRQ_PCMCIA	21
#define RTGALAXY_MISC_IRQ_CEC_TX	22
#define RTGALAXY_MISC_IRQ_CEC_RX	23
#define RTGALAXY_MISC_IRQ_SCARD0	24
#define RTGALAXY_MISC_IRQ_SCARD1	25
#define RTGALAXY_MISC_IRQ_I2C1		26

#define RTGALAXY_IRQ_USB		(RTGALAXY_IRQ_BASE+0)
#define RTGALAXY_IRQ_ETH		(RTGALAXY_IRQ_BASE+0)
#define RTGALAXY_IRQ_MISC		(RTGALAXY_IRQ_BASE+1)
#define RTGALAXY_IRQ_CP			(RTGALAXY_IRQ_BASE+1)
#define RTGALAXY_IRQ_1394		(RTGALAXY_IRQ_BASE+2)
#define RTGALAXY_IRQ_ATA		(RTGALAXY_IRQ_BASE+2)
#define RTGALAXY_IRQ_AUD		(RTGALAXY_IRQ_BASE+3)
#define RTGALAXY_IRQ_VID		(RTGALAXY_IRQ_BASE+3)
#define RTGALAXY_IRQ_SE			(RTGALAXY_IRQ_BASE+3)
#define RTGALAXY_IRQ_SB2		(RTGALAXY_IRQ_BASE+3)
#define RTGALAXY_IRQ_EXT_TIMER		(RTGALAXY_IRQ_BASE+4)
#define RTGALAXY_IRQ_TIMER		(RTGALAXY_IRQ_BASE+5)
#define RTGALAXY_IRQ_RTC		(RTGALAXY_IRQ_BASE+5)

#define RTGALAXY_IRQ_UART0		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_UART0)
#define RTGALAXY_IRQ_UART1		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_UART1)
#define RTGALAXY_IRQ_I2C0		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_I2C0)

#define RTGALAXY_IRQ_TIMER2		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_TIMER2)

#define RTGALAXY_IRQ_PCMCIA		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_PCMCIA)
#define RTGALAXY_IRQ_CEC_TX		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_CEC_TX)
#define RTGALAXY_IRQ_CEC_RX		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_CEC_RX)
#define RTGALAXY_IRQ_SCARD0		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_SCARD0)
#define RTGALAXY_IRQ_SCARD1		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_SCARD1)
#define RTGALAXY_IRQ_I2C1		(RTGALAXY_INTERNAL_IRQ_BASE+RTGALAXY_MISC_IRQ_I2C1)

#endif
