/*
 * This file is subject to the terms and conditions of the GNU General Public
 * License.  See the file "COPYING" in the main directory of this archive
 * for more details.
 *
 */

#ifndef _RTGALAXY_IO_H_
#define _RTGALAXY_IO_H_

/*
 * Internal registers are accessed through KSEG3
 */
#define RTGALAXY_REGS_VA(x)		((void __iomem *)(x))

#define rtgalaxy_readb(a)		(*(volatile unsigned char  *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_readw(a)		(*(volatile unsigned short *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_readl(a)		(*(volatile unsigned int   *) RTGALAXY_REGS_VA(a))
#define rtgalaxy_writeb(v, a)		(*(volatile unsigned char  *) RTGALAXY_REGS_VA((a)) = (v))
#define rtgalaxy_writew(v, a)		(*(volatile unsigned short *) RTGALAXY_REGS_VA((a)) = (v))
#define rtgalaxy_writel(v, a)		(*(volatile unsigned int   *) RTGALAXY_REGS_VA((a)) = (v))

#define RTGALAXY_REG_BASE		0x18010000

#define rtgalaxy_reg_readb(a)		rtgalaxy_readb(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_readw(a)		rtgalaxy_readw(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_readl(a)		rtgalaxy_readl(RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writeb(v, a)	rtgalaxy_writeb(v, RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writew(v, a)	rtgalaxy_writew(v, RTGALAXY_REG_BASE+a)
#define rtgalaxy_reg_writel(v, a)	rtgalaxy_writel(v, RTGALAXY_REG_BASE+a)

/*
 * rt-galaxy registers
 */

#define RTGALAXY_SYS_BASE_OFFSET		0x0000
#define RTGALAXY_EHCI_BASE_OFFSET		0x3000
#define RTGALAXY_UHCI_BASE_OFFSET		0x3400
#define RTGALAXY_USBH_BASE_OFFSET		0x3800
#define RTGALAXY_MCP_BASE_OFFSET		0x5100
#define RTGALAXY_ETH_BASE_OFFSET		0x6000
#define RTGALAXY_TVE_BASE_OFFSET		0x8000
#define RTGALAXY_TVD_BASE_OFFSET		0x9000
#define RTGALAXY_SB2_BASE_OFFSET		0xa000
#define RTGALAXY_MISC_BASE_OFFSET		0xb000
#define RTGALAXY_GPIO_BASE_OFFSET		0xb100
#define RTGALAXY_UART_BASE_OFFSET		0xb200
#define RTGALAXY_I2C0_BASE_OFFSET		0xb300
#define RTGALAXY_IRDA_BASE_OFFSET		0xb400
#define RTGALAXY_TIMR_BASE_OFFSET		0xb500
#define RTGALAXY_RTC_BASE_OFFSET		0xb600
#define RTGALAXY_VFDC_BASE_OFFSET		0xb700
#define RTGALAXY_PCMCIA_BASE_OFFSET		0xb800
#define RTGALAXY_CEC_BASE_OFFSET		0xb900
#define RTGALAXY_SC0_BASE_OFFSET		0xba00
#define RTGALAXY_I2C1_BASE_OFFSET		0xbb00
#define RTGALAXY_SC1_BASE_OFFSET		0xbc00

/*
 * Misc (PLL, IRQ ??)
 */

#define RTGALAXY_MISC_PSELH_OFFSET		0x000
#define RTGALAXY_MISC_PSELL_OFFSET		0x004
#define RTGALAXY_MISC_UMSK_ISR_OFFSET		0x008
#define RTGALAXY_MISC_ISR_OFFSET		0x00c
#define RTGALAXY_MISC_UMSK_ISR_GP0A_OFFSET	0x010
#define RTGALAXY_MISC_UMSK_ISR_GP0DA_OFFSET	0x014
#define RTGALAXY_MISC_UMSK_ISR_KPADAH_OFFSET	0x018
#define RTGALAXY_MISC_UMSK_ISR_KPADAL_OFFSET	0x01c
#define RTGALAXY_MISC_UMSK_ISR_KPADDAH_OFFSET	0x020
#define RTGALAXY_MISC_UMSK_ISR_KPADDAL_OFFSET	0x024
#define RTGALAXY_MISC_UMSK_ISR_SW_OFFSET	0x028
#define RTGALAXY_MISC_DBG_OFFSET		0x02c
#define RTGALAXY_MISC_DUMMY_OFFSET		0x030
#define RTGALAXY_MISC_PSEL2_OFFSET		0x034
#define RTGALAXY_MISC_UMSK_ISR_GP1A_OFFSET	0x038
#define RTGALAXY_MISC_UMSK_ISR_GP1DA_OFFSET	0x03c

#define RTGALAXY_MISC_BASE			(RTGALAXY_MISC_BASE_OFFSET)
#define RTGALAXY_MISC_PSELH			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSELH_OFFSET)
#define RTGALAXY_MISC_PSELL			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSELL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_OFFSET)
#define RTGALAXY_MISC_ISR			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_ISR_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP0A		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP0A_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP0DA		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP0DA_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADAH		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADAH_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADAL		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADAL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADDAH		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADDAH_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_KPADDAL		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_KPADDAL_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_SW		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_SW_OFFSET)
#define RTGALAXY_MISC_DBG			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_DBG_OFFSET)
#define RTGALAXY_MISC_DUMMY			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_DUMMY_OFFSET)
#define RTGALAXY_MISC_PSEL2			(RTGALAXY_MISC_BASE+RTGALAXY_MISC_PSEL2_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP1A		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP1A_OFFSET)
#define RTGALAXY_MISC_UMSK_ISR_GP1DA		(RTGALAXY_MISC_BASE+RTGALAXY_MISC_UMSK_ISR_GP1DA_OFFSET)

/*
 * UART0/UART1 (8250 compatible)
 */

#define RTGALAXY_UART_U0RBR_THR_DLL_OFFSET	0x000
#define RTGALAXY_UART_U0IER_DLH_OFFSET		0x004
#define RTGALAXY_UART_U0IIR_FCR_OFFSET		0x008
#define RTGALAXY_UART_U0LCR_OFFSET		0x00c
#define RTGALAXY_UART_U0MCR_OFFSET		0x010
#define RTGALAXY_UART_U0LSR_OFFSET		0x014
#define RTGALAXY_UART_U0MSR_OFFSET		0x018
#define RTGALAXY_UART_U0SCR_OFFSET		0x01c
#define RTGALAXY_UART_U1RBR_THR_DLL_OFFSET	0x020
#define RTGALAXY_UART_U1IER_DLH_OFFSET		0x024
#define RTGALAXY_UART_U1IIR_FCR_OFFSET		0x028
#define RTGALAXY_UART_U1LCR_OFFSET		0x02c
#define RTGALAXY_UART_U1MCR_OFFSET		0x030
#define RTGALAXY_UART_U1LSR_OFFSET		0x034
#define RTGALAXY_UART_U1MSR_OFFSET		0x038
#define RTGALAXY_UART_U1SCR_OFFSET		0x03c

#define RTGALAXY_UART_BASE			(RTGALAXY_UART_BASE_OFFSET)
#define RTGALAXY_UART_U0RBR_THR_DLL		(RTGALAXY_UART_BASE+RTGALAXY_UART_U0RBR_THR_DLL_OFFSET)
#define RTGALAXY_UART_U0IER_DLH			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0IER_DLH_OFFSET)
#define RTGALAXY_UART_U0IIR_FCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0IIR_FCR_OFFSET)
#define RTGALAXY_UART_U0LCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0LCR_OFFSET)
#define RTGALAXY_UART_U0MCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0MCR_OFFSET)
#define RTGALAXY_UART_U0LSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0LSR_OFFSET)
#define RTGALAXY_UART_U0MSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0MSR_OFFSET)
#define RTGALAXY_UART_U0SCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U0SCR_OFFSET)
#define RTGALAXY_UART_U1RBR_THR_DLL		(RTGALAXY_UART_BASE+RTGALAXY_UART_U1RBR_THR_DLL_OFFSET)
#define RTGALAXY_UART_U1IER_DLH			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1IER_DLH_OFFSET)
#define RTGALAXY_UART_U1IIR_FCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1IIR_FCR_OFFSET)
#define RTGALAXY_UART_U1LCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1LCR_OFFSET)
#define RTGALAXY_UART_U1MCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1MCR_OFFSET)
#define RTGALAXY_UART_U1LSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1LSR_OFFSET)
#define RTGALAXY_UART_U1MSR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1MSR_OFFSET)
#define RTGALAXY_UART_U1SCR			(RTGALAXY_UART_BASE+RTGALAXY_UART_U1SCR_OFFSET)

#define RTGALAXY_UART0_BASE			RTGALAXY_UART_U0RBR_THR_DLL
#define RTGALAXY_UART1_BASE			RTGALAXY_UART_U1RBR_THR_DLL

/*
 * Timer
 */

#define RTGALAXY_TIMR_TC0TVR_OFFSET		0x000
#define RTGALAXY_TIMR_TC1TVR_OFFSET		0x004
#define RTGALAXY_TIMR_TC2TVR_OFFSET		0x008
#define RTGALAXY_TIMR_TC0CVR_OFFSET		0x00c
#define RTGALAXY_TIMR_TC1CVR_OFFSET		0x010
#define RTGALAXY_TIMR_TC2CVR_OFFSET		0x014
#define RTGALAXY_TIMR_TC0CR_OFFSET		0x018
#define RTGALAXY_TIMR_TC1CR_OFFSET		0x01c
#define RTGALAXY_TIMR_TC2CR_OFFSET		0x020
#define RTGALAXY_TIMR_TC0ICR_OFFSET		0x024
#define RTGALAXY_TIMR_TC1ICR_OFFSET		0x028
#define RTGALAXY_TIMR_TC2ICR_OFFSET		0x02c
#define RTGALAXY_TIMR_TCWCR_OFFSET		0x030
#define RTGALAXY_TIMR_TCWTR_OFFSET		0x034
#define RTGALAXY_TIMR_CLK27M_CLK90K_CNT_OFFSET	0x038
#define RTGALAXY_TIMR_CLK90K_TM_LO_OFFSET	0x03c
#define RTGALAXY_TIMR_CLK90K_TM_HI_OFFSET	0x040

#define RTGALAXY_TIMR_BASE			(RTGALAXY_TIMR_BASE_OFFSET)
#define RTGALAXY_TIMR_TC0TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0TVR_OFFSET)
#define RTGALAXY_TIMR_TC1TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1TVR_OFFSET)
#define RTGALAXY_TIMR_TC2TVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2TVR_OFFSET)
#define RTGALAXY_TIMR_TC0CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0CVR_OFFSET)
#define RTGALAXY_TIMR_TC1CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1CVR_OFFSET)
#define RTGALAXY_TIMR_TC2CVR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2CVR_OFFSET)
#define RTGALAXY_TIMR_TC0CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0CR_OFFSET)
#define RTGALAXY_TIMR_TC1CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1CR_OFFSET)
#define RTGALAXY_TIMR_TC2CR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2CR_OFFSET)
#define RTGALAXY_TIMR_TC0ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC0ICR_OFFSET)
#define RTGALAXY_TIMR_TC1ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC1ICR_OFFSET)
#define RTGALAXY_TIMR_TC2ICR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TC2ICR_OFFSET)
#define RTGALAXY_TIMR_TCWCR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TCWCR_OFFSET)
#define RTGALAXY_TIMR_TCWTR			(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_TCWTR_OFFSET)
#define RTGALAXY_TIMR_CLK27M_CLK90K_CNT		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK27M_CLK90K_CNT_OFFSET)
#define RTGALAXY_TIMR_CLK90K_TM_LO		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK90K_TM_LO_OFFSET)
#define RTGALAXY_TIMR_CLK90K_TM_HI		(RTGALAXY_TIMR_BASE+RTGALAXY_TIMR_CLK90K_TM_HI_OFFSET)

/*
 * RTC
 */

#define RTGALAXY_RTC_SEC_OFFSET			0x000
#define RTGALAXY_RTC_MIN_OFFSET			0x004
#define RTGALAXY_RTC_HR_OFFSET			0x008
#define RTGALAXY_RTC_DATE1_OFFSET		0x00c
#define RTGALAXY_RTC_DATE2_OFFSET		0x010
#define RTGALAXY_RTC_ALMMIN_OFFSET		0x014
#define RTGALAXY_RTC_ALMHR_OFFSET		0x018
#define RTGALAXY_RTC_ALMDATE1_OFFSET		0x01c
#define RTGALAXY_RTC_ALMDATE2_OFFSET		0x020
#define RTGALAXY_RTC_STOP_OFFSET		0x024
#define RTGALAXY_RTC_ACR_OFFSET			0x028
#define RTGALAXY_RTC_EN_OFFSET			0x02c
#define RTGALAXY_RTC_CR_OFFSET			0x030

#define RTGALAXY_RTC_BASE			(RTGALAXY_RTC_BASE_OFFSET)
#define RTGALAXY_RTC_SEC			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_SEC_OFFSET)
#define RTGALAXY_RTC_MIN			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_MIN_OFFSET)
#define RTGALAXY_RTC_HR				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_HR_OFFSET)
#define RTGALAXY_RTC_DATE1			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_DATE1_OFFSET)
#define RTGALAXY_RTC_DATE2			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_DATE2_OFFSET)
#define RTGALAXY_RTC_ALMMIN			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMMIN_OFFSET)
#define RTGALAXY_RTC_ALMHR			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMHR_OFFSET)
#define RTGALAXY_RTC_ALMDATE1			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMDATE1_OFFSET)
#define RTGALAXY_RTC_ALMDATE2			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ALMDATE2_OFFSET)
#define RTGALAXY_RTC_STOP			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_STOP_OFFSET)
#define RTGALAXY_RTC_ACR			(RTGALAXY_RTC_BASE+RTGALAXY_RTC_ACR_OFFSET)
#define RTGALAXY_RTC_EN				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_EN_OFFSET)
#define RTGALAXY_RTC_CR				(RTGALAXY_RTC_BASE+RTGALAXY_RTC_CR_OFFSET)

/*
 * SB2
 */

#define RTGALAXY_SB2_HD_SEM_OFFSET		0x000
#define RTGALAXY_SB2_INV_INTEN_OFFSET		0x004
#define RTGALAXY_SB2_INV_INTSTAT_OFFSET		0x008
#define RTGALAXY_SB2_INV_ADDR_OFFSET		0x00c

#define RTGALAXY_SB2_CHIP_ID_OFFSET		0x200
#define RTGALAXY_SB2_CHIP_INFO_OFFSET		0x204

#define RTGALAXY_SB2_DBG_START_REG0_OFFSET	0x458
#define RTGALAXY_SB2_DBG_START_REG1_OFFSET	0x45c
#define RTGALAXY_SB2_DBG_START_REG2_OFFSET	0x460
#define RTGALAXY_SB2_DBG_START_REG3_OFFSET	0x464
#define RTGALAXY_SB2_DBG_START_REG4_OFFSET	0x468
#define RTGALAXY_SB2_DBG_START_REG5_OFFSET	0x46c
#define RTGALAXY_SB2_DBG_START_REG6_OFFSET	0x470
#define RTGALAXY_SB2_DBG_START_REG7_OFFSET	0x474

#define RTGALAXY_SB2_DBG_END_REG0_OFFSET	0x478
#define RTGALAXY_SB2_DBG_END_REG1_OFFSET	0x47c
#define RTGALAXY_SB2_DBG_END_REG2_OFFSET	0x480
#define RTGALAXY_SB2_DBG_END_REG3_OFFSET	0x484
#define RTGALAXY_SB2_DBG_END_REG4_OFFSET	0x488
#define RTGALAXY_SB2_DBG_END_REG5_OFFSET	0x48c
#define RTGALAXY_SB2_DBG_END_REG6_OFFSET	0x490
#define RTGALAXY_SB2_DBG_END_REG7_OFFSET	0x494

#define RTGALAXY_SB2_DBG_CTRL_REG0_OFFSET	0x498
#define RTGALAXY_SB2_DBG_CTRL_REG1_OFFSET	0x49c
#define RTGALAXY_SB2_DBG_CTRL_REG2_OFFSET	0x4a0
#define RTGALAXY_SB2_DBG_CTRL_REG3_OFFSET	0x4a4
#define RTGALAXY_SB2_DBG_CTRL_REG4_OFFSET	0x4a8
#define RTGALAXY_SB2_DBG_CTRL_REG5_OFFSET	0x4ac
#define RTGALAXY_SB2_DBG_CTRL_REG6_OFFSET	0x4b0
#define RTGALAXY_SB2_DBG_CTRL_REG7_OFFSET	0x4b4

#define RTGALAXY_SB2_DBG_ADDR_AUDIO_OFFSET	0x4b8
#define RTGALAXY_SB2_DBG_ADDR_VIDEO_OFFSET	0x4bc
#define RTGALAXY_SB2_DBG_ADDR_SYSTEM_OFFSET	0x4c0

#define RTGALAXY_SB2_DBG_INT_OFFSET		0x4e0

#define RTGALAXY_SB2_BASE			(RTGALAXY_SB2_BASE_OFFSET)
#define RTGALAXY_SB2_HD_SEM			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_HD_SEM_OFFSET)
#define RTGALAXY_SB2_INV_INTEN			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_INTEN_OFFSET)
#define RTGALAXY_SB2_INV_INTSTAT		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_INTSTAT_OFFSET)
#define RTGALAXY_SB2_INV_ADDR			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_INV_ADDR_OFFSET)

#define RTGALAXY_SB2_CHIP_ID			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_CHIP_ID_OFFSET)
#define RTGALAXY_SB2_CHIP_INFO			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_CHIP_INFO_OFFSET)

#define RTGALAXY_SB2_DBG_START_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_START_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_START_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_END_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_END_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_END_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_CTRL_REG0		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG0_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG1		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG1_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG2		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG2_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG3		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG3_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG4		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG4_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG5		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG5_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG6		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG6_OFFSET)
#define RTGALAXY_SB2_DBG_CTRL_REG7		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_CTRL_REG7_OFFSET)

#define RTGALAXY_SB2_DBG_ADDR_AUDIO		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_AUDIO_OFFSET)
#define RTGALAXY_SB2_DBG_ADDR_VIDEO		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_VIDEO_OFFSET)
#define RTGALAXY_SB2_DBG_ADDR_SYSTEM		(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_ADDR_SYSTEM_OFFSET)

#define RTGALAXY_SB2_DBG_INT			(RTGALAXY_SB2_BASE+RTGALAXY_SB2_DBG_INT_OFFSET)

#endif
