obj-$(CONFIG_RTGALAXY) += platform.o
obj-$(CONFIG_RTGALAXY) += irq.o
obj-$(CONFIG_RTGALAXY) += memory.o
obj-$(CONFIG_RTGALAXY) += prom.o
obj-$(CONFIG_RTGALAXY) += setup.o
obj-$(CONFIG_RTGALAXY) += time.o
obj-$(CONFIG_RTGALAXY) += board.o
obj-$(CONFIG_RTGALAXY) += printk.o
obj-$(CONFIG_RTGALAXY) += sb2.o

ifdef CONFIG_USB
obj-$(CONFIG_RTGALAXY) += usb.o
endif